name: deploy

on:
  push:
    branches:
      - master

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    environment: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Deploy
        run: npx ember deploy production --activate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DISTRIBUTION: ${{ vars.AWS_DISTRIBUTION }}
          REVISION: ${{ github.run_id }}
